/** @type {import('tailwindcss').Config} */
module.exports = {
  mode: "jit",
  darkMode: ["class", '[data-theme="dark"]'],
  content: ["src/**/*.tsx"],
  future: {
    hoverOnlyWhenSupported: true,
  },
  prefix: "",
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      transitionDuration: {
        250: "250ms",
        350: "350ms",
        400: "400ms",
        450: "450ms",
        550: "550ms",
        600: "600ms",
        650: "650ms",
        750: "750ms",
        800: "800ms",
        850: "850ms",
        900: "900ms",
        950: "950ms",
      },
      transitionTimingFunction: {
        1: "cubic-bezier(.25, 0, .5, 1)",
        2: "cubic-bezier(.25, 0, .4, 1)",
        3: "cubic-bezier(.25, 0, .3, 1)",
        4: "cubic-bezier(.25, 0, .2, 1)",
        5: "cubic-bezier(.25, 0, .1, 1)",
        "in-1": "cubic-bezier(.25, 0, 1, 1)",
        "in-2": "cubic-bezier(.50, 0, 1, 1)",
        "in-3": "cubic-bezier(.70, 0, 1, 1)",
        "in-4": "cubic-bezier(.90, 0, 1, 1)",
        "in-5": "cubic-bezier(1, 0, 1, 1)",
        "out-1": "cubic-bezier(0, 0, .75, 1)",
        "out-2": "cubic-bezier(0, 0, .50, 1)",
        "out-3": "cubic-bezier(0, 0, .3, 1)",
        "out-4": "cubic-bezier(0, 0, .1, 1)",
        "out-5": "cubic-bezier(0, 0, 0, 1)",
        "in-out-1": "cubic-bezier(.1, 0, .9, 1)",
        "in-out-2": "cubic-bezier(.3, 0, .7, 1)",
        "in-out-3": "cubic-bezier(.5, 0, .5, 1)",
        "in-out-4": "cubic-bezier(.7, 0, .3, 1)",
        "in-out-5": "cubic-bezier(.9, 0, .1, 1)",
        "elastic-1": "cubic-bezier(.5, .75, .75, 1.25)",
        "elastic-2": "cubic-bezier(.5, 1, .75, 1.25)",
        "elastic-3": "cubic-bezier(.5, 1.25, .75, 1.25)",
        "elastic-4": "cubic-bezier(.5, 1.5, .75, 1.25)",
        "elastic-5": "cubic-bezier(.5, 1.75, .75, 1.25)",
        "squish-1": "cubic-bezier(.5, -.1, .1, 1.5)",
        "squish-2": "cubic-bezier(.5, -.3, .1, 1.5)",
        "squish-3": "cubic-bezier(.5, -.5, .1, 1.5)",
        "squish-4": "cubic-bezier(.5, -.7, .1, 1.5)",
        "squish-5": "cubic-bezier(.5, -.9, .1, 1.5)",
        "step-1": "steps(2)",
        "step-2": "steps(3)",
        "step-3": "steps(4)",
        "step-4": "steps(7)",
        "step-5": "steps(10)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
